name: Test and deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test and lint the project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use PNPM package manager
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.6.1

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Check for linting errors
        id: lint
        run: |
          if pnpm run lint; then
            echo "lint-passed=true" >> $GITHUB_ENV
          else
            echo "lint-passed=false" >> $GITHUB_ENV
            exit 1
          fi

      - name: Build the project
        run: pnpm run build
        if: steps.lint.outputs.lint-passed == 'true'
